=== FRED-GSPH-PITT/FRED-Navigator-Classroom/xml-resources/jaxb/FredNavigatorBinding/frednavigator_questions.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://fred.pitt.edu/fred_navigator"
  xmlns="http://fred.pitt.edu/fred_navigator"
  elementFormDefault="qualified">
    
  <xsd:element name="quiz" type="quizType"/>
  
  <xsd:complexType name="quizType">   
    <xsd:sequence> 
      <xsd:element name="quizQuestion" minOccurs="1" maxOccurs="unbounded" type="fredNavigatorQuestionType"/>   
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="fredNavigatorQuestionType">   
    <xsd:sequence> 
      <xsd:element name="imageFileName" minOccurs="1" maxOccurs="1" type="xsd:string"/>     
      <xsd:element name="questionText" minOccurs="1" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="answerText" minOccurs="1" maxOccurs="1" type="xsd:string"/>      
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== FRED-GSPH-PITT/FRED-Navigator-Classroom/src/edu/pitt/phdl/frednavigator/resource/topicOneQuiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
These are the questions that make up topic one
They will be parsed in the FredNavigator Class and maintained as static
They will be used on the Predictions tab for Topic1
-->

<ns1:quiz
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://fred.pitt.edu/fred_navigator'
    xsi:schemaLocation='http://fred.pitt.edu/fred_navigator file:/Users/ddg5/FRED/FREDNavigatorClassroom/src/edu/pitt/phdl/frednavigator/resource/frednavigator_questions.xsd'>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic1_q1.png</ns1:imageFileName>
        <ns1:questionText>The red curve represents an incidence curve due to an epidemic with R0 = 1.5.</ns1:questionText>
        <ns1:answerText> Which of the other curves might represents an epidemic at the same place with R0 = 2.0?
            Why?</ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic1_q2.png</ns1:imageFileName>
        <ns1:questionText>The red curve represents an incidence curve due to an epidemic with R0 = 2.5.</ns1:questionText>
        <ns1:answerText> Which of the other curves represents an epidemic with R0 = 1.5?
            Why?</ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic1_q3.png</ns1:imageFileName>
        <ns1:questionText>The curve above represents the prevalence curve due to an epidemic with R0 = 1.6.</ns1:questionText>
        <ns1:answerText> About how many weeks will the epidemic last?
            How many days will more than 5000 people be infected?
            Would an epidemic with R0 = 2.0 last longer than the epidemic shown, or shorter?
            Why?</ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic1_q4.png</ns1:imageFileName>
        <ns1:questionText>The red curve above represents an attack rate curve due to an epidemic with R0 = 1.8.</ns1:questionText>
        <ns1:answerText> Which of the other curves might represent an attack rate curve?
            What values of R0 might be associated with the other attack rate curve?</ns1:answerText>
    </ns1:quizQuestion>
</ns1:quiz>

=== FRED-GSPH-PITT/FRED-Navigator-Classroom/src/edu/pitt/phdl/frednavigator/resource/topicThreeQuiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
These are the questions that make up topic three
They will be parsed in the FredNavigator Class and maintained as static
They will be used on the Predictions tab for Topic3
-->


<ns1:quiz
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://fred.pitt.edu/fred_navigator'
    xsi:schemaLocation='http://fred.pitt.edu/fred_navigator file:/Users/ddg5/FRED/FREDNavigatorClassroom/src/edu/pitt/phdl/frednavigator/resource/frednavigator_questions.xsd'>
    <ns1:quizQuestion>
      <ns1:imageFileName>topic3_q1.png</ns1:imageFileName>
      <ns1:questionText>The green curve represents an incidence with R0=1.4 with no school closure. The red curve represents an incidence curve if each school closes for 4 weeks once 10 students attending that school get sick. The school closure policy reduces incidence at first but then increases later.
      </ns1:questionText>
      <ns1:answerText> Why does this happen?
          Can you explain the timing of the second wave of illness?
      </ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
      <ns1:imageFileName>topic3_q2.png</ns1:imageFileName>
      <ns1:questionText>The green curve represents an attack rate curve with R0=1.4 with no school closure.  Let's call this the baseline. The red curve represents the attack rate curve if each school closes for 4 weeks once 10 students attending that school get sick.
      </ns1:questionText>
      <ns1:answerText> Can you explain the shape of the red attack rate curve?
          Would it be possible for the school closure attack rate to be higher than the baseline?
          Why or why not?
      </ns1:answerText>
    </ns1:quizQuestion>
</ns1:quiz>

=== FRED-GSPH-PITT/FRED-Navigator-Classroom/src/edu/pitt/phdl/frednavigator/resource/topicTwoQuiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
These are the questions that make up topic two
They will be parsed in the FredNavigator Class and maintained as static
They will be used on the Predictions tab for Topic2
-->


<ns1:quiz
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://fred.pitt.edu/fred_navigator'
    xsi:schemaLocation='http://fred.pitt.edu/fred_navigator file:/Users/ddg5/FRED/FREDNavigatorClassroom/src/edu/pitt/phdl/frednavigator/resource/frednavigator_questions.xsd'>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic2_q1.png</ns1:imageFileName>
        <ns1:questionText>The red curve represents an incidence curve due to an epidemic with R0 = 2.0 with no immunization in the population.</ns1:questionText>
        <ns1:answerText> Which of the other curves might represents an epidemic with R0 = 2.0 at the same place, if 30% of the population immunized?
            Why?
        </ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic2_q2.png</ns1:imageFileName>
        <ns1:questionText>The curves above show the incidence curves due to an epidemic with R0 = 2.4 if there is no immunity in the population and if half the population is immunized.</ns1:questionText>
        <ns1:answerText> When does the peak of the epidemic occur in both cases?
            How long does immunization delay the peak in this case?
            How might this affect the length of lines at health care clinics?
        </ns1:answerText>
    </ns1:quizQuestion>
    <ns1:quizQuestion>
        <ns1:imageFileName>topic2_q3.png</ns1:imageFileName>
        <ns1:questionText> The curves above show that the attack rate due to an epidemic with R0 = 2.4 is about 80% if there is no immunity in the population, but drops to about 20% if half the population is immunized.</ns1:questionText>
        <ns1:answerText>Why does immunizing 50% of the population decrease the number of people getting infected by 75% ?</ns1:answerText>
    </ns1:quizQuestion>
</ns1:quiz>
